AWSTemplateFormatVersion: 2010-09-09
Description: Redis Playground - ElastiCache for Redis cluster

Parameters:
  StackNamePrefix:
    Type: String

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub Security group for ${AWS::StackName}
      GroupName: !Sub ${AWS::StackName}-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
      VpcId: vpc-00fff691ee0d71c09
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }



  ParameterGroupRedis60:
    Type: 'AWS::ElastiCache::ParameterGroup'
    Properties:
      Description: !Sub Parameter Group for ${AWS::StackName} Redis cluster
      CacheParameterGroupFamily: redis5.0
      Properties:
        maxmemory-policy: allkeys-lru

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.t2.micro
      CacheParameterGroupName: !Ref ParameterGroupRedis60
      CacheSubnetGroupName: lk-subnet
      Engine: redis
      EngineVersion: 5.0.6
      ReplicasPerNodeGroup: 1
      PreferredMaintenanceWindow: mon:07:30-mon:08:30
      ReplicationGroupId: !Sub ${AWS::StackName}
      ReplicationGroupDescription: !Sub Redis Cluster ${AWS::StackName}
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      SnapshotRetentionLimit: 0
      TransitEncryptionEnabled: true
      MultiAZEnabled: true
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}' }
Outputs:
  PrimaryAddress:
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Address
  PrimaryPort:
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Port
